/** Defines the event types generated by SignalingClient and the underlying WebSocket connection. */
export declare enum SignalingClientEventType {
    WebSocketConnecting = 0,
    WebSocketOpen = 1,
    WebSocketError = 2,
    WebSocketClosing = 3,
    WebSocketClosed = 4,
    WebSocketFailed = 5,
    WebSocketMessage = 6,
    WebSocketSendMessageFailure = 7,
    WebSocketSentMessage = 8,
    ProtocolDecodeFailure = 9,
    ReceivedSignalFrame = 10,
    WebSocketSkippedMessage = 11
}
export default SignalingClientEventType;
