import Logger from '../logger/Logger';
import MeetingSession from '../meetingsession/MeetingSession';
import CheckAudioConnectivityFeedback from './CheckAudioConnectivityFeedback';
import CheckAudioInputFeedback from './CheckAudioInputFeedback';
import CheckAudioOutputFeedback from './CheckAudioOutputFeedback';
import CheckCameraResolutionFeedback from './CheckCameraResolutionFeedback';
import CheckContentShareConnectivityFeedback from './CheckContentShareConnectivityFeedback';
import CheckNetworkTCPConnectivityFeedback from './CheckNetworkTCPConnectivityFeedback';
import CheckNetworkUDPConnectivityFeedback from './CheckNetworkUDPConnectivityFeedback';
import CheckVideoConnectivityFeedback from './CheckVideoConnectivityFeedback';
import CheckVideoInputFeedback from './CheckVideoInputFeedback';
import MeetingReadinessChecker from './MeetingReadinessChecker';
import MeetingReadinessCheckerConfiguration from './MeetingReadinessCheckerConfiguration';
export default class DefaultMeetingReadinessChecker implements MeetingReadinessChecker {
    private logger;
    private meetingSession;
    private configuration;
    private static delay;
    private audioContext;
    private gainNode;
    private oscillatorNode;
    private destinationStream;
    private originalURLRewriter;
    private browserBehavior;
    constructor(logger: Logger, meetingSession: MeetingSession, configuration?: MeetingReadinessCheckerConfiguration);
    checkAudioInput(audioInputDeviceInfo: MediaDeviceInfo): Promise<CheckAudioInputFeedback>;
    checkAudioOutput(audioOutputDeviceInfo: MediaDeviceInfo, audioOutputVerificationCallback: () => Promise<boolean>, audioElement?: HTMLAudioElement): Promise<CheckAudioOutputFeedback>;
    private playTone;
    private stopTone;
    checkVideoInput(videoInputDeviceInfo: MediaDeviceInfo): Promise<CheckVideoInputFeedback>;
    checkCameraResolution(videoInputDevice: MediaDeviceInfo, width: number, height: number): Promise<CheckCameraResolutionFeedback>;
    private calculateVideoConstraint;
    checkContentShareConnectivity(sourceId?: string): Promise<CheckContentShareConnectivityFeedback>;
    checkAudioConnectivity(audioInputDeviceInfo: MediaDeviceInfo): Promise<CheckAudioConnectivityFeedback>;
    checkVideoConnectivity(videoInputDeviceInfo: MediaDeviceInfo): Promise<CheckVideoConnectivityFeedback>;
    checkNetworkUDPConnectivity(): Promise<CheckNetworkUDPConnectivityFeedback>;
    checkNetworkTCPConnectivity(): Promise<CheckNetworkTCPConnectivityFeedback>;
    private startMeeting;
    private stopMeeting;
    private executeTimeoutTask;
}
