/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_cognito_identity_pool_id": "ap-northeast-2:8c8c941e-e4cc-4301-a29f-9b65ba206ca0",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_6BH8m4f8z",
    "aws_user_pools_web_client_id": "1nf0h801mqastdkhd6gchosm5a",
    "oauth": {}
};


export default awsmobile;
